In [32]:
import numpy as np
np.random.seed(1)

In [33]:
x = np.array([113,122,107,98,115,120,118])
x2 = np.array([6.8,4.7,5.2,3.6,2.9,4.2,5.1])

x = np.vstack((x,x2))  
y = np.array([0,1,0,0,1,1,1])

w = 2*np.random.random((1,3)) - 1

e = np.zeros(7)
eta = 0.1
bias = 1

for i in range(1000):
    for k in range(6):
        xb = np.hstack((bias,x[:,k]))
        yr = np.tanh(np.dot(w,xb))
        e[k] = y[k]-yr
        w += eta*e[k]*xb
print(w)
print("Vetor de errors (e) = " + str(e))



[[113.  122.  107.   98.  115.  120.  118. ]
 [  6.8   4.7   5.2   3.6   2.9   4.2   5.1]]
[  1.  113.    6.8]
[  1.  122.    4.7]
[  1.  107.    5.2]
[ 1.  98.   3.6]
[  1.  115.    2.9]
[  1.  120.    4.2]
[  1.  113.    6.8]
[  1.  122.    4.7]
[  1.  107.    5.2]
[ 1.  98.   3.6]
[  1.  115.    2.9]
[  1.  120.    4.2]
[  1.  113.    6.8]
[  1.  122.    4.7]
[  1.  107.    5.2]
[ 1.  98.   3.6]
[  1.  115.    2.9]
[  1.  120.    4.2]
[  1.  113.    6.8]
[  1.  122.    4.7]
[  1.  107.    5.2]
[ 1.  98.   3.6]
[  1.  115.    2.9]
[  1.  120.    4.2]
[  1.  113.    6.8]
[  1.  122.    4.7]
[  1.  107.    5.2]
[ 1.  98.   3.6]
[  1.  115.    2.9]
[  1.  120.    4.2]
[  1.  113.    6.8]
[  1.  122.    4.7]
[  1.  107.    5.2]
[ 1.  98.   3.6]
[  1.  115.    2.9]
[  1.  120.    4.2]
[  1.  113.    6.8]
[  1.  122.    4.7]
[  1.  107.    5.2]
[ 1.  98.   3.6]
[  1.  115.    2.9]
[  1.  120.    4.2]
[  1.  113.    6.8]
[  1.  122.    4.7]
[  1.  107.    5.2]
[ 1.  98.   3.6]
[  1.  115.  

C:\Users\juand\AppData\Local\Temp\ipykernel_123748\2312924464.py:20: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  e[k] = y[k]-yr


[ 1.  98.   3.6]
[  1.  115.    2.9]
[  1.  120.    4.2]
[  1.  113.    6.8]
[  1.  122.    4.7]
[  1.  107.    5.2]
[ 1.  98.   3.6]
[  1.  115.    2.9]
[  1.  120.    4.2]
[  1.  113.    6.8]
[  1.  122.    4.7]
[  1.  107.    5.2]
[ 1.  98.   3.6]
[  1.  115.    2.9]
[  1.  120.    4.2]
[  1.  113.    6.8]
[  1.  122.    4.7]
[  1.  107.    5.2]
[ 1.  98.   3.6]
[  1.  115.    2.9]
[  1.  120.    4.2]
[  1.  113.    6.8]
[  1.  122.    4.7]
[  1.  107.    5.2]
[ 1.  98.   3.6]
[  1.  115.    2.9]
[  1.  120.    4.2]
[  1.  113.    6.8]
[  1.  122.    4.7]
[  1.  107.    5.2]
[ 1.  98.   3.6]
[  1.  115.    2.9]
[  1.  120.    4.2]
[  1.  113.    6.8]
[  1.  122.    4.7]
[  1.  107.    5.2]
[ 1.  98.   3.6]
[  1.  115.    2.9]
[  1.  120.    4.2]
[  1.  113.    6.8]
[  1.  122.    4.7]
[  1.  107.    5.2]
[ 1.  98.   3.6]
[  1.  115.    2.9]
[  1.  120.    4.2]
[  1.  113.    6.8]
[  1.  122.    4.7]
[  1.  107.    5.2]
[ 1.  98.   3.6]
[  1.  115.    2.9]
[  1.  120.    4.2]
[  1.  

In [34]:
X = np.array([ [0,0,1],[0,1,1],[1,0,1],[1,1,1] ])
y = np.array([[0,1,1,0]]).T
syn0 = 2*np.random.random((3,4)) - 1
syn1 = 2*np.random.random((4,1)) - 1
for j in range(60000):
    l1 = 1/(1+np.exp(-(np.dot(X,syn0))))
    l2 = 1/(1+np.exp(-(np.dot(l1,syn1))))
    l2_delta = (y - l2)*(l2*(1-l2))
    l1_delta = l2_delta.dot(syn1.T) * (l1 * (1-l1))
    syn1 += l1.T.dot(l2_delta)
    syn0 += X.T.dot(l1_delta)

In [35]:
l1 = 1/(1+np.exp(-(np.dot([0,0,0],syn0))))
l2 = 1/(1+np.exp(-(np.dot(l1,syn1))))

print(l2)

[0.03023714]
