In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
numEpocas = 100   
q = 13               
eta = 0.01            
m = 2                 
N = 4                 
L = 1       

In [3]:
peso = np.array([113, 122, 107,  98, 115, 120, 104, 108, 117, 101, 112, 106, 116])
pH   = np.array([6.8, 4.7, 5.2, 3.6, 2.9, 4.2, 6.3, 4.0, 6.3, 4.2, 5.6, 3.1, 5.0])
d = np.array([-1, 1, -1, 1, 1, 1, -1, 1, -1, 1, -1, 1, -1])
W1 = np.random.random((N, m + 1))
W2 = np.random.random((L, N + 1))
bias = 1
X = np.vstack((peso, pH))
E = np.zeros(q)
Etm = np.zeros(numEpocas) 


In [4]:
print(W1)

[[0.17490158 0.52382696 0.91747062]
 [0.20125511 0.24156671 0.58240349]
 [0.04163022 0.18856143 0.24210873]
 [0.47087823 0.25034603 0.66099109]]


In [6]:
for i in range(numEpocas):
    for j in range(len(X[0])):
        Xb = np.hstack((bias,X[:,j]))
        o1 = np.tanh(W1.dot(Xb))
        o1b = np.insert(o1,0,bias)
        Y = np.tanh(W2.dot(o1b))
        e = d[j] - Y
        E[j] = (e.transpose().dot(e))/2
        delta2 = np.diag(e).dot((1 - Y*Y))        
        vdelta2 = (W2.transpose()).dot(delta2)      
        delta1 = np.diag(1 - o1b*o1b).dot(vdelta2) 
        W1 = W1 + eta*(np.outer(delta1[1:], Xb))
        W2 = W2 + eta*(np.outer(delta2, o1b))
Etm[i] = E.mean()

